import AppKit
import Observation

@Observable final class Store {
    var data = AppData()
    var clipboard: [Clip] = []
    var clipboardEnabled = true
    var notice: String?
    var persistenceError: String?
    let directory: URL
    private var pasteboardChange: Int
    private var polling: Task<Void, Never>?
    private var seenScreenshots = Set<String>()
    private var tick = 0

    init(directory: URL? = nil, startMonitoring: Bool = true) {
        self.directory = directory ?? FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0].appendingPathComponent("Socius")
        pasteboardChange = NSPasteboard.general.changeCount
        do {
            try FileManager.default.createDirectory(at: self.directory, withIntermediateDirectories: true)
            let file = self.directory.appendingPathComponent("data.json")
            if FileManager.default.fileExists(atPath: file.path) {
                data = try JSONDecoder().decode(AppData.self, from: Data(contentsOf: file))
            }
        } catch { persistenceError = "Could not load saved data: \(error.localizedDescription). The original file will not be overwritten." }
        if startMonitoring {
            polling = Task { [weak self] in
                while !Task.isCancelled {
                    self?.poll()
                    try? await Task.sleep(for: .seconds(1))
                }
            }
        }
    }
    func stop() { polling?.cancel() }
    func save() {
        guard persistenceError == nil else { return }
        do {
            let encoder = JSONEncoder(); encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
            try encoder.encode(data).write(to: directory.appendingPathComponent("data.json"), options: .atomic)
        } catch { notice = "Could not save: \(error.localizedDescription)" }
    }
    func reward(_ message: String) {
        data.pet.helpfulActions += 1
        notice = message
        save()
    }
    func copy(_ text: String) {
        let board = NSPasteboard.general
        board.clearContents(); board.setString(text, forType: .string)
        pasteboardChange = board.changeCount
        reward("Copied. A little less typing!")
    }
    func poll() {
        let board = NSPasteboard.general
        if board.changeCount != pasteboardChange {
            pasteboardChange = board.changeCount
            let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
            if clipboardEnabled && !excluded.contains(where: { board.availableType(from: [NSPasteboard.PasteboardType($0)]) != nil }) {
                if let text = board.string(forType: .string), !text.isEmpty, text.utf8.count <= 1_000_000 {
                    recordClip(text)
                } else if let image = NSImage(pasteboard: board), let tiff = image.tiffRepresentation,
                          let bitmap = NSBitmapImageRep(data: tiff), let png = bitmap.representation(using: .png, properties: [:]) {
                    do {
                        let vault = directory.appendingPathComponent("Screenshots")
                        try FileManager.default.createDirectory(at: vault, withIntermediateDirectories: true)
                        let url = vault.appendingPathComponent("Capture-\(UUID().uuidString.prefix(8)).png")
                        try png.write(to: url, options: .atomic)
                        addFiles([url])
                    } catch { notice = "Could not save clipboard image: \(error.localizedDescription)" }
                }
            }
        }
        tick += 1
        if tick % 5 == 0 { scanScreenshots() }
    }
    func recordClip(_ text: String) {
        clipboard.removeAll { $0.text == text }
        clipboard.insert(Clip(text: text), at: 0)
        clipboard = Array(clipboard.prefix(40))
    }
    func addFiles(_ urls: [URL]) {
        for url in urls where url.isFileURL && FileManager.default.fileExists(atPath: url.path) {
            guard !data.shelf.contains(where: { $0.path == url.path }) else { continue }
            data.shelf.insert(ShelfItem(path: url.path), at: 0)
        }
        data.shelf = Array(data.shelf.prefix(100)); save()
    }
    func chooseFiles() {
        let panel = NSOpenPanel(); panel.allowsMultipleSelection = true
        panel.canChooseDirectories = false
        if panel.runModal() == .OK { addFiles(panel.urls) }
    }
    func chooseScreenshotFolder() {
        let panel = NSOpenPanel(); panel.canChooseDirectories = true; panel.canChooseFiles = false
        panel.message = "Choose where macOS saves your screenshots. Socius will show the most recent images here."
        if panel.runModal() == .OK, let url = panel.url {
            data.screenshotFolder = url.path; seenScreenshots.removeAll(); save(); scanScreenshots()
        }
    }
    func scanScreenshots() {
        guard let path = data.screenshotFolder else { return }
        do {
            let urls = try FileManager.default.contentsOfDirectory(at: URL(fileURLWithPath: path), includingPropertiesForKeys: [.creationDateKey], options: .skipsHiddenFiles)
            let images = urls.filter { ["png", "jpg", "jpeg", "heic"].contains($0.pathExtension.lowercased()) }
                .sorted { ((try? $0.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast) > ((try? $1.resourceValues(forKeys: [.creationDateKey]).creationDate) ?? .distantPast) }
            let recent = Array(images.prefix(20))
            let new = recent.filter { !seenScreenshots.contains($0.path) }
            seenScreenshots.formUnion(recent.map(\.path))
            if !new.isEmpty { addFiles(new.reversed()) }
        } catch { notice = "Screenshot folder unavailable: \(error.localizedDescription)" }
    }
    func feed() { data.pet.lastFed = Date(); reward("Mochi says: nom nom. Thank you!") }
    func play() { data.pet.lastPlayed = Date(); reward("A tiny adventure, just for us.") }
}
